package com.oskarro.muzikum.monitor;

public enum StatusCode {

    /** 1xx Informational Response */
    STATUS_100_CONTINUE,

    /** 2xx Success */
    STATUS_200_OK,
    STATUS_201_CREATED,
    STATUS_202_ACCEPTED,
    STATUS_204_NO_CONTENT,
    STATUS_205_RESET_CONTENT,

    /** 3xx Redirection */
    STATUS_300_MULTIPLE_CHOICES,
    STATUS_301_MOVED_PERMANENTLY,
    STATUS_302_FOUND,
    STATUS_303_SEE_OTHER,

    /** 4xx Client errors */
    STATUS_400_BAD_REQUEST,
    STATUS_401_UNAUTHORIZED,
    STATUS_402_PAYMENT_REQUIRED,
    STATUS_403_FORBIDDEN,
    STATUS_404_NOT_FOUND,
    STATUS_405_METHOD_NOT_ALLOWED,
    STATUS_406_NOT_ACCEPTABLE,
    STATUS_408_REQUEST_TIMEOUT,

    /** 5xx Server errors */
    STATUS_500_INTERNAL_SERVER_ERROR,
    STATUS_501_NOT_IMPLEMENTED,
    STATUS_502_BAD_GATEWAY,
    STATUS_503_SERVICE_UNAVAILABLE,
    STATUS_504_GATEWAY_TIMEOUT,

    STATUS_OTHER
}
