spring:
  jpa:
    hibernate:
      ddl-auto: create  # creates the schema, destroying any previous data
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/muzikum_db"
    username: admin
    password: Osasuna1
